name: Publish Helm Chart to GitHub Pages

on:
  push:
    tags:
      - 'helm-v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Set up chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.6.0

      - name: Configure Git user
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Run chart-releaser
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p .cr-release-packages
          helm package deploy/helm --destination .cr-release-packages
          cr upload -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} --package-path .cr-release-packages
          cr index -o ${{ github.repository_owner }} -r ${{ github.event.repository.name }} -c https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Push index.yaml to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: .
          enable_jekyll: false
        if: success()
